all:
	g++ -std=c++17 -pthread main.cpp DefaultMultiplication.hpp Strassen.hpp Matrix.hpp Utils.hpp

debug:
	g++ -g -std=c++17 -pthread main.cpp DefaultMultiplication.hpp Strassen.hpp Matrix.hpp Utils.hpp

clean:
	rm a.out DefaultMultiplication.hpp.gch Strassen.hpp.gch Matrix.hpp.gch Utils.hpp.gch